name: Analyse code with Lint
on: [push]
jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Lint check
        run: npm run lint -s
